### PR TITLE
Add $debounce and $throttle

### PR DESCRIPTION
**Pull request by SimoTod**

### CODE REVIEW

**Review by ryangjchandler — APPROVED** [review]

**Review by KevinBatdorf — APPROVED** [review]

**Comment by tanthammar** [comment]
@SimoTod 
Thank you for adding these here, and for making it work.
I couldn't figure out how to keep the scope.

**Comment by SimoTod** [comment]
No worries. I wonder if we need them though. Alpine has already 2 modifiers for those. Do you have anything in mind that can't be achieved using `.debounce` and `.throttle`?

**Comment by SimoTod** [comment]
@tanthammar Alpine now expose debounce and throttle via `Alpine.debounce` and `Alpine.thottle` (although I don't agree with the implementation of the latter) so I'm going to close this PR without merging it.

**Comment by tanthammar** [comment]
@SimoTod Thank you for keeping track of this topic. Can you share your opinion on what you think is missing?

**Comment by SimoTod** [comment]
If you have a throttleling interval of 1sec and you click 2 times, Alpine runs the calback once and discards the second call. To me, that's just debouncing with immediate = true (https://davidwalsh.name/javascript-debounce-function old article, i know). 

Throttle should execute the first callback, then wait 1sec and execute the second callback too.

However, if you google it, people can't agree on the topic, someone prefers the Alpine implementation someone doesn't so both are valid implementations.

**Comment by tanthammar** [comment]
I read the same article (amongst others) :), and also noticed the two different basecamps for what's considered "true" throttling/debounce functionality.

I'm keeping your version locally, just giving it a different name so I can pick the one most suited for each case.

Again, thank you!

**Pull request closed without merging**
